cmake_minimum_required(VERSION 3.26)

# Destructive/failure checks use disposable fixtures, never the real checkout.
file(REMOVE_RECURSE "${TEST_ROOT}")
set(source "${TEST_ROOT}/source with spaces")
set(binary "${TEST_ROOT}/build with spaces")
file(MAKE_DIRECTORY "${source}/cmake" "${source}/share/trick")
foreach(path IN ITEMS CMakeLists.txt cmake/TrickVersion.cmake cmake/TrickVersionInfo.cmake.in share/trick/trick_ver.txt)
    configure_file("${TRICK_SOURCE}/${path}" "${source}/${path}" COPYONLY)
endforeach()
file(WRITE "${source}/Makefile" "# sentinel: legacy Makefile must survive\n")

function(run_configure)
    execute_process(COMMAND "${CMAKE_COMMAND}" -S "${source}" -B "${binary}"
        -G "${GENERATOR}" "-DCMAKE_MAKE_PROGRAM=${MAKE_PROGRAM}"
        "-DCMAKE_C_COMPILER=${C_COMPILER}" "-DCMAKE_CXX_COMPILER=${CXX_COMPILER}"
        -DBUILD_TESTING=OFF
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Configure failed: ${output}\n${error}")
    endif()
endfunction()

function(expect_failure expected_text)
    execute_process(COMMAND ${ARGN}
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(result EQUAL 0 OR NOT "${output}\n${error}" MATCHES "${expected_text}")
        message(FATAL_ERROR "Expected '${expected_text}', got ${result}: ${output}\n${error}")
    endif()
endfunction()

if(CASE STREQUAL "in-source")
    expect_failure("requires an out-of-source build"
        "${CMAKE_COMMAND}" -S "${source}" -B "${source}")
    file(READ "${source}/Makefile" sentinel)
    if(NOT sentinel STREQUAL "# sentinel: legacy Makefile must survive\n")
        message(FATAL_ERROR "Legacy Makefile was overwritten")
    endif()
    file(CREATE_LINK "${source}" "${TEST_ROOT}/source-alias" SYMBOLIC)
    expect_failure("requires an out-of-source build"
        "${CMAKE_COMMAND}" -S "${source}" -B "${TEST_ROOT}/source-alias")
elseif(CASE STREQUAL "minimum-version")
    expect_failure("CMake 3.26 or higher is required"
        "${OLD_CMAKE}" -S "${source}" -B "${binary}")
elseif(CASE STREQUAL "invalid-version")
    foreach(bad IN ITEMS "not-a-version" "25.1" "25.1.2\"\ncurrent_version = \"26.0.0")
        file(WRITE "${source}/share/trick/trick_ver.txt" "current_version = \"${bad}\"\n")
        expect_failure("Invalid Trick version"
            "${CMAKE_COMMAND}" -S "${source}" -B "${binary}" -DBUILD_TESTING=OFF)
    endforeach()
elseif(CASE STREQUAL "version")
    foreach(version IN ITEMS 27.0.0 27.0.0-rc.1 27.0.0+build.2)
        file(WRITE "${source}/share/trick/trick_ver.txt" "current_version = \"${version}\"\n")
        run_configure()
        include("${binary}/TrickVersionInfo.cmake")
        if(NOT TRICK_VERSION STREQUAL version OR NOT TRICK_VERSION_NUMBER STREQUAL "27.0.0")
            message(FATAL_ERROR "Version or suffix was not preserved")
        endif()
    endforeach()
else()
    # Globbing here verifies fixture contents; it does not select build sources.
    file(GLOB_RECURSE inputs RELATIVE "${source}" "${source}/*")
    foreach(path IN LISTS inputs)
        file(SHA256 "${source}/${path}" "before_${path}")
    endforeach()
    run_configure()
    if(CASE STREQUAL "install")
        expect_failure("cannot install an SDK"
            "${CMAKE_COMMAND}" --install "${binary}" --prefix "${TEST_ROOT}/install")
    elseif(CASE STREQUAL "regeneration")
        # Make the input newer even on coarse-resolution filesystems.
        execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 1)
        file(WRITE "${source}/share/trick/trick_ver.txt" "current_version = \"28.1.2-beta\"\n")
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" --build "${binary}" --config Debug
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Preview build failed: ${output}\n${error}")
    endif()
    if(CASE STREQUAL "regeneration")
        include("${binary}/TrickVersionInfo.cmake")
        if(NOT TRICK_VERSION STREQUAL "28.1.2-beta")
            message(FATAL_ERROR "Editing trick_ver.txt did not trigger regeneration")
        endif()
        list(REMOVE_ITEM inputs share/trick/trick_ver.txt)
    endif()
    foreach(path IN LISTS inputs)
        file(SHA256 "${source}/${path}" after)
        if(NOT after STREQUAL "${before_${path}}")
            message(FATAL_ERROR "Source input changed: ${path}")
        endif()
    endforeach()
    file(GLOB_RECURSE after_inputs RELATIVE "${source}" "${source}/*")
    if(CASE STREQUAL "regeneration")
        list(REMOVE_ITEM after_inputs share/trick/trick_ver.txt)
    endif()
    if(NOT inputs STREQUAL after_inputs)
        message(FATAL_ERROR "Build added or removed source files")
    endif()
endif()
