cmake_minimum_required(VERSION 3.26)
file(REMOVE_RECURSE "${TEST_ROOT}")
set(legacy "${TEST_ROOT}/legacy")
set(home "${TEST_ROOT}/home")
set(maps "${legacy}/trick_source/sim_services/include/io_src")
file(MAKE_DIRECTORY "${legacy}/io" "${maps}" "${home}/share/trick/xml/include")
# Legacy SIE output uses TRICK_HOME; give it writable data directories without
# copying or writing production sources. Header classification uses real paths.
file(CREATE_LINK "${TRICK_SOURCE}/include" "${home}/include" SYMBOLIC)
file(CREATE_LINK "${TRICK_SOURCE}/trick_source" "${home}/trick_source" SYMBOLIC)
execute_process(COMMAND "${CMAKE_COMMAND}" -E env "TRICK_HOME=${home}"
    "${ICG}" ${FRONTEND_FLAGS} -sim_services -m -force --icg-std=c++17 ${DEFINITIONS}
    "-I${TRICK_SOURCE}/include" "-I${TRICK_SOURCE}/trick_source"
    "-I${TRICK_SOURCE}/include/trick/compat" "-isystem${UDUNITS_INCLUDE}"
    -o "${legacy}/io" "${TRICK_SOURCE}/include/trick/files_to_ICG.hh"
    WORKING_DIRECTORY "${legacy}" RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
file(WRITE "${TEST_ROOT}/legacy.log" "${output}\n${error}")
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Legacy-layout core generation failed: ${error}")
endif()
get_filename_component(native "${MANIFEST}" DIRECTORY)
foreach(map IN ITEMS class_map.cpp extern_init_attr.h)
    file(SHA256 "${native}/${map}" expected)
    file(SHA256 "${maps}/${map}" actual)
    if(NOT expected STREQUAL actual)
        message(FATAL_ERROR "Output layout changed core ${map}")
    endif()
endforeach()
file(READ "${MANIFEST}" manifest)
string(JSON count LENGTH "${manifest}" headers)
math(EXPR last "${count} - 1")
set(names)
foreach(index RANGE 0 ${last})
    string(JSON header GET "${manifest}" headers ${index} header)
    string(JSON generated GET "${manifest}" headers ${index} output)
    file(READ "${generated}" expected)
    if(expected STREQUAL "// No metadata in this configuration.\n")
        continue()
    endif()
    get_filename_component(name "${header}" NAME_WLE)
    if(name IN_LIST names)
        message(FATAL_ERROR "Core parity fixture needs separate legacy invocations for duplicate basename: ${name}")
    endif()
    list(APPEND names "${name}")
    file(READ "${legacy}/io/io_${name}.cpp" actual)
    if(NOT expected STREQUAL actual)
        message(FATAL_ERROR "Output layout changed core metadata: ${header}")
    endif()
endforeach()
list(LENGTH names compared)
message(STATUS "Compared ${compared} core metadata sources and both registration maps across output layouts")
