cmake_minimum_required(VERSION 3.26)
file(REAL_PATH "${ROOT}" ROOT)
file(READ "${MANIFEST}" manifest)
file(STRINGS "${INVENTORY}" expected)
string(JSON count LENGTH "${manifest}" headers)
list(LENGTH expected expected_count)
if(NOT count EQUAL expected_count)
    message(FATAL_ERROR "Core manifest and declared graph disagree: ${count} vs ${expected_count}")
endif()
math(EXPR last "${count} - 1")
foreach(index RANGE 0 ${last})
    string(JSON header GET "${manifest}" headers ${index} header)
    string(JSON output GET "${manifest}" headers ${index} output)
    list(FIND expected "${header}" found)
    if(found LESS 0 OR NOT output STREQUAL "${ROOT}/io${header}.cpp" OR NOT EXISTS "${output}")
        message(FATAL_ERROR "Unexpected or missing core output: ${header} -> ${output}")
    endif()
    list(REMOVE_ITEM expected "${header}")
endforeach()
if(expected OR NOT EXISTS "${ROOT}/generation.stamp")
    message(FATAL_ERROR "Incomplete core generation: ${expected}")
endif()
