cmake_minimum_required(VERSION 3.26)
file(REMOVE_RECURSE "${TEST_ROOT}")
file(MAKE_DIRECTORY "${TEST_ROOT}/source")
set(source "${TEST_ROOT}/source")
set(binary "${TEST_ROOT}/build")

function(configure_case expected)
    execute_process(COMMAND "${CMAKE_COMMAND}" -S "${source}" -B "${binary}"
        -G "${GENERATOR}" "-DCMAKE_MAKE_PROGRAM=${MAKE_PROGRAM}"
        "-DCMAKE_C_COMPILER=${C_COMPILER}" "-DCMAKE_CXX_COMPILER=${CXX_COMPILER}"
        ${ARGN} RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(expected STREQUAL "pass")
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "Configure failed: ${output}\n${error}")
        endif()
    elseif(result EQUAL 0 OR NOT "${output}\n${error}" MATCHES "${expected}")
        message(FATAL_ERROR "Expected '${expected}', got ${result}: ${output}\n${error}")
    endif()
endfunction()

set(preamble "cmake_minimum_required(VERSION 3.26)\nproject(DependencyFixture LANGUAGES C CXX)\n")
if(CASE MATCHES "^gcc-")
    file(WRITE "${source}/CMakeLists.txt" "${preamble}include(\"${TRICK_SOURCE}/cmake/TrickCompilers.cmake\")\ntrick_check_compiler(C GNU ${VERSION})\ntrick_check_compiler(CXX GNU ${VERSION})\n")
    if(VERSION VERSION_LESS 8.5)
        configure_case("requires GCC >=8.5")
    else()
        configure_case(pass)
    endif()
elseif(CASE STREQUAL "minimal" OR CASE STREQUAL "invalid-profile")
    file(WRITE "${source}/CMakeLists.txt" "${preamble}include(\"${TRICK_SOURCE}/cmake/TrickDependencies.cmake\")\n")
    if(CASE STREQUAL "minimal")
        configure_case(pass -DCMAKE_DISABLE_FIND_PACKAGE_Python3=ON -DCMAKE_DISABLE_FIND_PACKAGE_LLVM=ON
            -DCMAKE_DISABLE_FIND_PACKAGE_GTest=ON -DCMAKE_DISABLE_FIND_PACKAGE_X11=ON
            -DCMAKE_DISABLE_FIND_PACKAGE_SWIG=ON -DCMAKE_DISABLE_FIND_PACKAGE_UDUNITS2=ON)
    else()
        configure_case("Invalid TRICK_DEPENDENCY_PROFILE" -DTRICK_DEPENDENCY_PROFILE=RUNTME)
    endif()
elseif(CASE MATCHES "^llvm-")
    # Synthetic package metadata tests selection/error paths, not LLVM usability.
    set(prefix "${TEST_ROOT}/selected prefix")
    file(MAKE_DIRECTORY "${prefix}/llvm" "${prefix}/clang" "${TEST_ROOT}/other/clang")
    set(version 14.0.6)
    if(CASE STREQUAL "llvm-old")
        set(version 13.0.1)
    endif()
    file(WRITE "${prefix}/llvm/LLVMConfig.cmake" "set(LLVM_PACKAGE_VERSION ${version})\nadd_library(LLVMSupport INTERFACE IMPORTED)\n")
    file(MAKE_DIRECTORY "${prefix}/include/clang/Basic")
    set(clang_version 14)
    if(CASE STREQUAL "llvm-header-mismatch")
        set(clang_version 13)
    endif()
    file(WRITE "${prefix}/include/clang/Basic/Version.inc" "#define CLANG_VERSION_MAJOR ${clang_version}\n")
    file(WRITE "${prefix}/clang/ClangConfig.cmake" "add_library(clangTooling INTERFACE IMPORTED)\nset(CLANG_INCLUDE_DIRS \"${prefix}/include\")\n")
    file(WRITE "${source}/CMakeLists.txt" "${preamble}include(\"${TRICK_SOURCE}/cmake/TrickLLVM.cmake\")\n")
    if(CASE STREQUAL "llvm-old")
        configure_case("requires LLVM >=14" "-DLLVM_DIR=${prefix}/llvm")
    elseif(CASE STREQUAL "llvm-header-mismatch")
        configure_case("major versions disagree" "-DLLVM_DIR=${prefix}/llvm")
    elseif(CASE STREQUAL "llvm-mismatch")
        configure_case("sibling config packages" "-DLLVM_DIR=${prefix}/llvm" "-DClang_DIR=${TEST_ROOT}/other/clang")
    elseif(CASE STREQUAL "llvm-missing")
        file(REMOVE "${prefix}/clang/ClangConfig.cmake")
        configure_case("Clang" "-DLLVM_DIR=${prefix}/llvm")
    else()
        # Explicit selection wins over an unrelated prefix; include symlink layout.
        file(CREATE_LINK "${prefix}/llvm" "${TEST_ROOT}/llvm-alias" SYMBOLIC)
        configure_case(pass "-DLLVM_DIR=${TEST_ROOT}/llvm-alias" "-DCMAKE_PREFIX_PATH=${TEST_ROOT}/other")
    endif()
elseif(CASE STREQUAL "udunits-root")
    file(WRITE "${source}/CMakeLists.txt" "${preamble}list(APPEND CMAKE_MODULE_PATH \"${TRICK_SOURCE}/cmake/modules\")\nfind_package(UDUNITS2 REQUIRED)\n")
    configure_case("Install UDUNITS-2" "-DUDUNITS2_ROOT=${TEST_ROOT}/missing-prefix")
elseif(CASE STREQUAL "python-major")
    file(WRITE "${source}/CMakeLists.txt" "${preamble}include(\"${TRICK_SOURCE}/cmake/TrickPython.cmake\")\n")
    configure_case("TRICK_PYTHON_MAJOR must be 2 or 3" -DTRICK_PYTHON_MAJOR=4)
endif()

if(CASE STREQUAL "python-embed" OR CASE STREQUAL "python-mismatch")
    if(CASE STREQUAL "python-mismatch")
        execute_process(COMMAND "${PYTHON_EXECUTABLE}" -c "import sys; print('%d.%d' % sys.version_info[:2])" OUTPUT_VARIABLE python_version OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
        file(MAKE_DIRECTORY "${TEST_ROOT}/wrong")
        file(WRITE "${TEST_ROOT}/wrong/wrong.c" "const char *Py_GetVersion(void) { return \"0.0\"; }\nvoid Py_Initialize(void) {}\nint Py_IsInitialized(void) { return 1; }\nvoid Py_Finalize(void) {}\n")
        file(WRITE "${TEST_ROOT}/wrong/CMakeLists.txt" "${preamble}add_library(wrong SHARED wrong.c)\nset_target_properties(wrong PROPERTIES OUTPUT_NAME python${python_version})\nfile(GENERATE OUTPUT \"${TEST_ROOT}/wrong-$<CONFIG>.txt\" CONTENT \"$<TARGET_FILE:wrong>\")\n")
        execute_process(COMMAND "${CMAKE_COMMAND}" -S "${TEST_ROOT}/wrong" -B "${TEST_ROOT}/wrong-build"
            -G "${GENERATOR}" "-DCMAKE_MAKE_PROGRAM=${MAKE_PROGRAM}" "-DCMAKE_C_COMPILER=${C_COMPILER}" "-DCMAKE_CXX_COMPILER=${CXX_COMPILER}"
            -DCMAKE_BUILD_TYPE=Debug RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "Fixture configure failed: ${out}\n${err}")
        endif()
        execute_process(COMMAND "${CMAKE_COMMAND}" --build "${TEST_ROOT}/wrong-build" --config Debug
            RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "Fixture build failed: ${out}\n${err}")
        endif()
        file(READ "${TEST_ROOT}/wrong-Debug.txt" PYTHON_LIBRARY)
        set(expected "do not")
    else()
        set(expected pass)
    endif()
    file(WRITE "${source}/CMakeLists.txt" "${preamble}include(\"${TRICK_SOURCE}/cmake/TrickPython.cmake\")\n")
    configure_case("${expected}" "-DTRICK_PYTHON_MAJOR=${PYTHON_MAJOR}"
        "-DPython${PYTHON_MAJOR}_EXECUTABLE=${PYTHON_EXECUTABLE}"
        "-DPython${PYTHON_MAJOR}_INCLUDE_DIR=${PYTHON_INCLUDE_DIR}"
        "-DPython${PYTHON_MAJOR}_LIBRARY=${PYTHON_LIBRARY}")
endif()

if(CASE MATCHES "^udunits-(selected|mismatch)$")
    set(prefix "${TEST_ROOT}/units prefix")
    file(MAKE_DIRECTORY "${prefix}/include" "${prefix}/lib" "${TEST_ROOT}/library")
    file(WRITE "${prefix}/include/udunits2.h" "typedef struct ut_system ut_system;\nut_system *ut_read_xml(const char *);\nvoid ut_free_system(ut_system *);\n")
    if(CASE STREQUAL "udunits-selected")
        set(body "void *ut_read_xml(const char *path) { return 0; }\nvoid ut_free_system(void *p) {}\n")
        set(expected pass)
    else()
        set(body "int unrelated(void) { return 0; }\n")
        set(expected "UDUNITS2 headers/library do not link")
    endif()
    file(WRITE "${TEST_ROOT}/library/units.c" "${body}")
    file(WRITE "${TEST_ROOT}/library/CMakeLists.txt" "${preamble}add_library(udunits2 STATIC units.c)\ninstall(TARGETS udunits2 ARCHIVE DESTINATION lib)\n")
    execute_process(COMMAND "${CMAKE_COMMAND}" -S "${TEST_ROOT}/library" -B "${TEST_ROOT}/library-build"
        -G "${GENERATOR}" "-DCMAKE_MAKE_PROGRAM=${MAKE_PROGRAM}"
        "-DCMAKE_C_COMPILER=${C_COMPILER}" "-DCMAKE_CXX_COMPILER=${CXX_COMPILER}"
        "-DCMAKE_INSTALL_PREFIX=${prefix}"
        RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Fixture configure failed: ${out}\n${err}")
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" --build "${TEST_ROOT}/library-build" --config Debug
        RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Fixture build failed: ${out}\n${err}")
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" --install "${TEST_ROOT}/library-build" --config Debug
        RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Fixture install failed: ${out}\n${err}")
    endif()
    file(WRITE "${source}/CMakeLists.txt" "${preamble}list(APPEND CMAKE_MODULE_PATH \"${TRICK_SOURCE}/cmake/modules\")\nfind_package(UDUNITS2 REQUIRED)\nif(NOT UDUNITS2_INCLUDE_DIR STREQUAL \"${prefix}/include\")\nmessage(FATAL_ERROR \"Explicit root lost\")\nendif()\n")
    configure_case("${expected}" "-DUDUNITS2_ROOT=${prefix}")
endif()
