cmake_minimum_required(VERSION 3.26)
file(REMOVE_RECURSE "${TEST_ROOT}")
file(MAKE_DIRECTORY "${TEST_ROOT}/input/a" "${TEST_ROOT}/input/b" "${TEST_ROOT}/work")
# Duplicate basenames, distinct extensions, and an input with no declarations.
file(WRITE "${TEST_ROOT}/input/a/State.hh" "struct StateA { double x; };\n")
file(WRITE "${TEST_ROOT}/input/b/State.hh" "struct StateB { int x; };\n")
file(WRITE "${TEST_ROOT}/input/a/State.h" "struct StateC { int x; };\n")
file(WRITE "${TEST_ROOT}/input/transitive.hh" "#define ARRAY_SIZE 3\n")
file(WRITE "${TEST_ROOT}/input/All.hh" "#include \"a/State.hh\"\n#include \"b/State.hh\"\n#include \"a/State.h\"\n#include \"transitive.hh\"\nstruct All { int x[ARRAY_SIZE]; };\n")
set(root "${TEST_ROOT}/output with spaces")
function(generate expected)
    execute_process(COMMAND "${CMAKE_COMMAND}" -E env --unset=TRICK_HOME TRICK_CXX=
        "${ICG}" --output-root "${root}" ${inventory_args} ${system_args} "${TEST_ROOT}/input/All.hh"
        WORKING_DIRECTORY "${TEST_ROOT}/work" RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(expected AND NOT result EQUAL 0)
        message(FATAL_ERROR "ICG failed: ${output}\n${error}")
    elseif(NOT expected AND result EQUAL 0)
        message(FATAL_ERROR "ICG unexpectedly succeeded")
    endif()
endfunction()
generate(TRUE)
file(READ "${root}/manifest.json" manifest)
string(JSON count LENGTH "${manifest}" headers)
if(NOT count EQUAL 4)
    message(FATAL_ERROR "Expected four distinct generated headers: ${manifest}")
endif()
foreach(index RANGE 0 3)
    string(JSON output GET "${manifest}" headers ${index} output)
    if(NOT EXISTS "${output}")
        message(FATAL_ERROR "Missing output: ${output}")
    endif()
endforeach()
file(READ "${root}/dependencies.d" deps)
if(NOT deps MATCHES "transitive.hh" OR NOT EXISTS "${root}/generation.stamp")
    message(FATAL_ERROR "Missing transitive dependency or successful stamp")
endif()
# No output may leak into the working directory.
file(GLOB leaked "${TEST_ROOT}/work/*")
if(leaked)
    message(FATAL_ERROR "ICG wrote outside output root: ${leaked}")
endif()
# Deleted outputs are recreated; SIE append output is reset on every run.
file(SHA256 "${root}/classes.resource" first)
file(REMOVE "${output}")
generate(TRUE)
file(SHA256 "${root}/classes.resource" second)
if(NOT first STREQUAL second OR NOT EXISTS "${output}")
    message(FATAL_ERROR "Regeneration is incomplete or accumulates SIE entries")
endif()
file(APPEND "${TEST_ROOT}/input/transitive.hh" "\nthis is invalid C++;\n")
generate(FALSE)
if(EXISTS "${root}/generation.stamp" OR EXISTS "${root}/manifest.json")
    message(FATAL_ERROR "Failed generation published success")
endif()
# An empty translation unit still has maps, dependency information and a stamp.
file(WRITE "${TEST_ROOT}/input/All.hh" "// no declarations\n")
generate(TRUE)
file(READ "${root}/manifest.json" manifest)
string(JSON count LENGTH "${manifest}" headers)
if(NOT count EQUAL 0 OR NOT EXISTS "${root}/class_map.cpp")
    message(FATAL_ERROR "Empty generation failed")
endif()
# A write error also invalidates success from a previous invocation.
file(REMOVE "${root}/classes.resource")
file(MAKE_DIRECTORY "${root}/classes.resource")
generate(FALSE)
if(EXISTS "${root}/generation.stamp" OR EXISTS "${root}/manifest.json")
    message(FATAL_ERROR "Output failure retained a success record")
endif()

# The declared output inventory supplies stubs for empty/inactive headers and
# rejects newly generated headers until the build graph has been updated.
file(REMOVE_RECURSE "${root}/classes.resource")
file(WRITE "${TEST_ROOT}/inventory.txt" "${TEST_ROOT}/input/All.hh\n${TEST_ROOT}/input/a/State.hh\n")
set(inventory_args --output-inventory "${TEST_ROOT}/inventory.txt")
generate(TRUE)
file(READ "${root}/manifest.json" manifest)
string(JSON count LENGTH "${manifest}" headers)
if(NOT count EQUAL 2)
    message(FATAL_ERROR "Missing empty inventory outputs")
endif()
file(WRITE "${TEST_ROOT}/input/All.hh" "#include \"b/State.hh\"\n")
generate(FALSE)
if(EXISTS "${root}/generation.stamp")
    message(FATAL_ERROR "Inventory mismatch published success")
endif()

# Dependencies installed in compiler include directories must not reorder the
# compiler's C/C++ wrappers (notably UDUNITS in /usr/include on Ubuntu).
set(inventory_args)
foreach(path IN LISTS SYSTEM_INCLUDES)
    list(PREPEND system_args "-isystem${path}")
endforeach()
file(WRITE "${TEST_ROOT}/input/All.hh" "#include <cstdlib>\n#include <string>\nstruct NativeIncludes { int x; };\n")
generate(TRUE)
