cmake_minimum_required(VERSION 3.26)
file(REMOVE_RECURSE "${TEST_ROOT}")
file(MAKE_DIRECTORY "${TEST_ROOT}/consumer")
file(COPY "${CONSUMER}/" DESTINATION "${TEST_ROOT}/consumer")
function(run)
    execute_process(COMMAND ${ARGN} WORKING_DIRECTORY "${TEST_ROOT}"
        RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err)
    file(APPEND "${TEST_ROOT}/package-validation.log" "${ARGN}\n${out}${err}\n")
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "Package consumer failed: ${ARGN}\n${out}${err}")
    endif()
endfunction()
set(options "-DCMAKE_BUILD_TYPE=Release" "-DTrick_DIR=${PACKAGE_ROOT}" "-DCMAKE_DISABLE_FIND_PACKAGE_LLVM=TRUE"
    "-DCMAKE_DISABLE_FIND_PACKAGE_Clang=TRUE" "-DCMAKE_DISABLE_FIND_PACKAGE_SWIG=TRUE"
    "-DCMAKE_DISABLE_FIND_PACKAGE_BISON=TRUE" "-DCMAKE_DISABLE_FIND_PACKAGE_FLEX=TRUE")
if(HINTS)
    list(APPEND options -C "${HINTS}")
endif()
run("${CMAKE_COMMAND}" -S "${TEST_ROOT}/consumer" -B "${TEST_ROOT}/build" ${options})
run("${CMAKE_COMMAND}" --build "${TEST_ROOT}/build" --config Release --parallel 2)
run("${CMAKE_CTEST_COMMAND}" --test-dir "${TEST_ROOT}/build" -C Release --output-on-failure)
# A utilities-only C++ consumer needs neither embedding Python nor generators.
file(MAKE_DIRECTORY "${TEST_ROOT}/utilities")
file(WRITE "${TEST_ROOT}/utilities/CMakeLists.txt" [=[
cmake_minimum_required(VERSION 3.26)
project(TrickUtilityConsumer LANGUAGES CXX)
find_package(Trick CONFIG REQUIRED COMPONENTS Utilities)
add_executable(units main.cpp)
target_link_libraries(units PRIVATE Trick::Units)
enable_testing()
add_test(NAME units COMMAND units)
]=])
file(WRITE "${TEST_ROOT}/utilities/main.cpp"
    "#include <trick/Unit.hh>\nint main() { Unit metres(\"m\"); return metres.Convert_to(1.0, \"cm\") == 100.0 ? 0 : 1; }\n")
run("${CMAKE_COMMAND}" -S "${TEST_ROOT}/utilities" -B "${TEST_ROOT}/utilities-build" ${options}
    -DCMAKE_DISABLE_FIND_PACKAGE_Python2=TRUE -DCMAKE_DISABLE_FIND_PACKAGE_Python3=TRUE)
run("${CMAKE_COMMAND}" --build "${TEST_ROOT}/utilities-build" --config Release)
run("${CMAKE_CTEST_COMMAND}" --test-dir "${TEST_ROOT}/utilities-build" -C Release --output-on-failure)
file(MAKE_DIRECTORY "${TEST_ROOT}/invalid")
file(WRITE "${TEST_ROOT}/invalid/CMakeLists.txt"
    "cmake_minimum_required(VERSION 3.26)\nproject(Invalid LANGUAGES CXX)\nfind_package(Trick CONFIG REQUIRED COMPONENTS NotAComponent)\n")
execute_process(COMMAND "${CMAKE_COMMAND}" -S "${TEST_ROOT}/invalid" -B "${TEST_ROOT}/invalid-build" ${options}
    RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err)
if(status EQUAL 0 OR NOT "${out}${err}" MATCHES "Trick_FOUND to FALSE")
    message(FATAL_ERROR "Unknown required component was not diagnosed: ${out}${err}")
endif()
if(FORBIDDEN_SOURCE AND FORBIDDEN_BUILD)
    file(GLOB exports "${PACKAGE_ROOT}/*.cmake")
    foreach(export IN LISTS exports)
        file(READ "${export}" contents)
        string(FIND "${contents}" "${FORBIDDEN_SOURCE}" source_found)
        string(FIND "${contents}" "${FORBIDDEN_BUILD}" build_found)
        if(NOT source_found EQUAL -1 OR NOT build_found EQUAL -1)
            message(FATAL_ERROR "Installed package leaks a producer path: ${export}")
        endif()
    endforeach()
endif()
