cmake_minimum_required(VERSION 3.26)
foreach(required IN ITEMS SDK FIXTURE TEST_ROOT)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "Missing ${required}")
    endif()
endforeach()
file(REAL_PATH "${SDK}" SDK)
file(REMOVE_RECURSE "${TEST_ROOT}")
file(MAKE_DIRECTORY "${TEST_ROOT}")
file(COPY "${FIXTURE}/" DESTINATION "${TEST_ROOT}")
function(run)
    execute_process(COMMAND "${CMAKE_COMMAND}" -E env --unset=TRICK_HOME --unset=TRICK_PYTHON_PATH
        --unset=MAKEFLAGS "PYTHONDONTWRITEBYTECODE=1" ${ARGN}
        WORKING_DIRECTORY "${TEST_ROOT}" RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err)
    file(APPEND "${TEST_ROOT}/acceptance.log" "${ARGN}\n${out}${err}\n")
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "SDK command failed (${status}): ${ARGN}\n${out}${err}")
    endif()
    set(result "${out}" PARENT_SCOPE)
endfunction()
run("${SDK}/bin/trick-config" --prefix)
string(STRIP "${result}" prefix)
if(NOT prefix STREQUAL SDK)
    message(FATAL_ERROR "trick-config prefix mismatch: ${prefix} != ${SDK}")
endif()
run("${SDK}/bin/trick-config" --libdir)
string(STRIP "${result}" config_libdir)
run("${SDK}/bin/trick-gte" TRICK_LIB_DIR)
string(STRIP "${result}" gte_libdir)
if(NOT config_libdir STREQUAL gte_libdir OR NOT EXISTS "${gte_libdir}/libtrick.a")
    message(FATAL_ERROR "SDK readers disagree: ${config_libdir} / ${gte_libdir}")
endif()
# A gcc earlier on PATH must not replace the configured compiler identity.
run("${SDK}/bin/trick-gte" TRICK_HOST_CPU)
set(host_cpu "${result}")
file(MAKE_DIRECTORY "${TEST_ROOT}/fake-tools")
file(WRITE "${TEST_ROOT}/fake-tools/gcc" "#!/bin/sh\necho 99.99.0\n")
file(CHMOD "${TEST_ROOT}/fake-tools/gcc" PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE)
run("${CMAKE_COMMAND}" -E env "PATH=${TEST_ROOT}/fake-tools:$ENV{PATH}"
    "${SDK}/bin/trick-gte" TRICK_HOST_CPU)
if(NOT result STREQUAL host_cpu)
    message(FATAL_ERROR "gte ignored the SDK compiler when identifying the host")
endif()
# Compare the effective Make language mode with the recorded probe, including
# when CMAKE_CXX_FLAGS contains an earlier conflicting -std option.
run("${SDK}/bin/trick-config" --cxxflags)
separate_arguments(model_flags UNIX_COMMAND "${result}")
run("${SDK}/bin/trick-gte" TRICK_CXX)
string(STRIP "${result}" model_compiler)
run("${model_compiler}" ${model_flags} -dM -E -x c++ /dev/null)
string(REGEX MATCH "#define __cplusplus [0-9]+L" actual_standard "${result}")
file(READ "${SDK}/share/trick/model-predefines.txt" recorded)
string(REGEX MATCH "#define __cplusplus [0-9]+L" recorded_standard "${recorded}")
if(NOT actual_standard STREQUAL recorded_standard)
    message(FATAL_ERROR "Model language mode differs from the predefine probe")
endif()
run("${SDK}/bin/trick-CP")
file(GLOB executable "${TEST_ROOT}/S_main_*.exe")
list(LENGTH executable count)
if(NOT count EQUAL 1)
    message(FATAL_ERROR "Expected one simulation executable: ${executable}")
endif()
run("${CMAKE_COMMAND}" -E env "TRICK_HOME=${SDK}" "${executable}" RUN_test/input.py)
if(NOT EXISTS "${TEST_ROOT}/sdk-input-ran")
    message(FATAL_ERROR "Input file did not run")
endif()
file(READ "${TEST_ROOT}/sdk-input-ran" marker)
if(NOT marker STREQUAL "12.5\n")
    message(FATAL_ERROR "Incorrect model value: ${marker}")
endif()

# Normal late user settings must survive, but may not change the SDK compiler.
file(READ "${TEST_ROOT}/S_overrides.mk" overrides)
file(APPEND "${TEST_ROOT}/S_overrides.mk" "TRICK_ICGFLAGS += -DUSER_SDK_FLAG=1\n")
file(READ "${TEST_ROOT}/S_define" definition)
file(WRITE "${TEST_ROOT}/FlagCheck.hh" "#ifdef TRICK_ICG\n#ifndef USER_SDK_FLAG\n#error user ICG flag was dropped\n#endif\n#endif\nstruct FlagCheck { int value; };\n")
file(WRITE "${TEST_ROOT}/S_define" "${definition}\n##include \"FlagCheck.hh\"\n")
run("${SDK}/bin/trick-CP")
foreach(compiler IN ITEMS TRICK_CC TRICK_CXX)
    file(WRITE "${TEST_ROOT}/S_overrides.mk" "${overrides}\n${compiler} = definitely-not-the-sdk-compiler\n")
    execute_process(COMMAND "${CMAKE_COMMAND}" -E env --unset=TRICK_HOME --unset=MAKEFLAGS
        "${SDK}/bin/trick-CP" WORKING_DIRECTORY "${TEST_ROOT}"
        RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if(status EQUAL 0 OR NOT "${out}${err}" MATCHES "build a separate SDK")
        message(FATAL_ERROR "Late ${compiler} override was not rejected: ${out}${err}")
    endif()
endforeach()
file(REMOVE "${TEST_ROOT}/S_overrides.mk")
