#!/usr/bin/env python3
"""Generate bounded legacy C++ metadata from validated facts and resolved policy."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
from tools.icg_emit import lifecycle  # noqa: E402
from tools.icg_policy import resolve as policy  # noqa: E402
from tools.icg_policy.rules import PolicyError  # noqa: E402

VERSION = "scalar-metadata-emitter-8"


def literal(value: str) -> str:
    """Encode UTF-8 bytes without C++ escape greediness or universal characters."""
    if "\0" in value:
        raise PolicyError(
            "ICG_EMIT_STRING", "embedded NUL cannot form runtime metadata"
        )
    return (
        '"'
        + "".join(
            chr(ch) if 32 <= ch < 127 and ch not in (34, 63, 92) else f"\\{ch:03o}"
            for ch in value.encode("utf-8")
        )
        + '"'
    )


def contexts(node: dict, nodes: dict) -> list[dict]:
    result = []
    parent = nodes.get(node.get("semantic_parent_id"))
    while parent is not None:
        result.insert(0, parent)
        parent = nodes.get(parent.get("semantic_parent_id"))
    return result


def qualified(node: dict, nodes: dict) -> str:
    return "::".join(n["name"] for n in [*contexts(node, nodes), node])


def attribute(
    name="",
    spelling="",
    units="1",
    description="",
    io=15,
    mods=0,
    kind="TRICK_VOID",
    size="0",
    offset=0,
    width=0,
    shift=0,
    dimensions=(),
) -> str:
    entries = (
        [f"{{{extent}, 0}}" for extent in dimensions]
        if dimensions
        else [f"{{{width}, {shift}}}"]
    )
    indices = ", ".join(entries + ["{0, 0}"] * (8 - len(entries)))
    return (
        f'{{{literal(name)}, {literal(spelling)}, {literal(units)}, "", "",\n'
        f"  {literal(description)},\n"
        f"  {io},{kind}, {size}, 0, 0, Language_CPP, {mods},\n"
        f"  {offset}, NULL, {len(dimensions)}, {{{indices}}},\n"
        "  TRICK_STL_UNKNOWN, TRICK_NUMBER_OF_TYPES, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL}"
    )


def render(facts: dict, request: dict, resolved: dict) -> str:
    # Never accept a caller's checksum as proof that its policy is valid.
    policy.validate(facts, request, resolved)
    nodes = {n["id"]: n for n in facts["declarations"]}
    files = {n["id"]: n for n in facts["files"]}
    decisions = {d["declaration_id"]: d for d in resolved["declarations"]}
    selected = [
        nodes[i]
        for i, d in decisions.items()
        if d["decision"] == "include" and nodes[i]["kind"] in ("record", "enum")
    ]
    if not selected and not resolved["template_instances"]:
        raise PolicyError(
            "ICG_EMIT_EMPTY", "request selects no record or enum metadata"
        )
    target = facts["provenance"]["target_triple"]
    if not re.fullmatch(r"(x86_64|aarch64|arm64)-.*(linux|darwin|macos).*", target):
        raise PolicyError(
            "ICG_EMIT_TARGET",
            f"target outside audited little-endian LP64 profile: {target}",
        )
    # Numeric offsets belong to these exact source bytes. This is a local
    # development backend, not an offline/relocatable source cache.
    for file in files.values():
        path = Path(file["path"]["real"])
        if (
            not path.is_file()
            or hashlib.sha256(path.read_bytes()).hexdigest() != file["digest"]
        ):
            raise PolicyError("ICG_EMIT_SOURCE", f"source changed or missing: {path}")
    header = files[facts["provenance"]["translation_unit"]]["path"]["real"]
    if any(ch in header for ch in ('"', "\\", "\n", "\r")):
        raise PolicyError("ICG_EMIT_SOURCE", "input path cannot form a C++ include")
    chunks = [
        f"// Generated by {VERSION}; resolved policy {resolved['digest']}.\n"
        f"// Input identity: {resolved['input_digest']}.\n"
        f"// Requested outputs: {', '.join(request['outputs'])}. No STL, registries, SIE, or build files.\n"
        "#define TRICK_IN_IOSRC\n"
        "#include <climits>\n#include <cstddef>\n#include <limits>\n#include <type_traits>\n"
        '#include "trick/attributes.h"\n#include "trick/UnitsMap.hh"\n'
        f'#include "{header}"\n'
        "#if !defined(__BYTE_ORDER__) || __BYTE_ORDER__ != __ORDER_LITTLE_ENDIAN__\n"
        '#error "ICG metadata requires the audited little-endian target"\n#endif\n'
        'static_assert(CHAR_BIT == 8 && sizeof(int) == 4 && sizeof(double) == 8 && sizeof(long) == 8 && sizeof(void*) == 8, "ICG scalar ABI mismatch");\n'
        'static_assert(sizeof(bool) == 1 && sizeof(char) == 1 && sizeof(float) == 4 && std::numeric_limits<float>::is_iec559 && std::numeric_limits<float>::digits == 24, "ICG bool/char/float ABI mismatch");\n'
    ]
    if "lifecycle" in request["outputs"]:
        chunks.append(lifecycle.PREAMBLE)
    work = [
        (node, decisions[node["id"]]["metadata"], qualified(node, nodes), decisions)
        for node in selected
    ]
    for instance in resolved["template_instances"]:
        # An alias avoids passing template-argument commas to the offsetof macro.
        alias = "IcgTemplate_" + instance["symbol"]
        chunks.append(f"using {alias} = ::{instance['cpp_type']};\n")
        work.append((
            nodes[instance["record_id"]],
            dict(
                symbol=instance["symbol"],
                init_function=instance["init_function"],
                lifecycle=None,
            ),
            alias,
            {d["declaration_id"]: d for d in instance["fields"]},
        ))
    if any(i["dependency_record_ids"] for i in resolved["template_instances"]):
        chunks.append('#include "trick/MemoryManager.hh"\n')
    # A stable order independent of the supplied declaration-array ordering.
    for node, meta, name, field_decisions in sorted(
        work, key=lambda item: item[1]["symbol"]
    ):
        symbol = meta["symbol"]
        chunks.append(
            f'static_assert(sizeof(::{name}) * CHAR_BIT == {node["size_bits"]} && alignof(::{name}) * CHAR_BIT == {node["alignment_bits"]}, "ICG layout mismatch: {name}");\n'
        )
        if node["kind"] == "enum":
            enum = meta["enum"]
            rows = []
            chunks.append(
                f'static_assert(std::is_signed<std::underlying_type<::{name}>::type>::value == {str(node["underlying_signed"]).lower()}, "ICG enum signedness mismatch");\n'
            )
            for item in enum["rows"]:
                rows.append(
                    f"{{{literal(item['label'])}, {item['value']}, {hex(enum['mods'])}}}"
                )
                chunks.append(
                    f'static_assert(static_cast<long long>(::{item["cpp_name"]}) == {item["value"]}, "ICG enum value mismatch");\n'
                )
            chunks.append(
                'extern "C" {\n'
                + f"ENUM_ATTR enum{symbol}[] = {{\n"
                + ",\n".join(rows + ['{"", 0, 0x0}'])
                + f"\n}};\nsize_t io_src_sizeof_{symbol}() {{ return sizeof(::{name}); }}\n}}\n"
            )
            continue
        if meta["lifecycle"] is not None:
            chunks.append(lifecycle.render(node, meta, name))
        if not set(request["outputs"]) & {"attributes", "template-attributes"}:
            continue
        if not node["standard_layout"]:
            raise PolicyError(
                "ICG_EMIT_RECORD",
                f"non-standard-layout metadata is outside this emitter profile: {name}",
            )
        for friend in node["friends"]:
            signature = friend["signature"]
            if (
                friend["target_kind"] == "function"
                and friend["target_qualified_name"] == meta["init_function"]
                and not signature["method"]
                and not signature["parameter_type_usrs"]
                and not signature["variadic"]
                and (
                    not signature["returns_void"]
                    or signature["noexcept"] != "false"
                    or signature["language_linkage"] != "c++"
                )
            ):
                raise PolicyError(
                    "ICG_EMIT_INIT",
                    f"friend declaration conflicts with the generated init signature: {name}",
                )
        rows, checks, units, registrations = [], [], [], []
        for identifier in node["field_ids"]:
            decision = field_decisions[identifier]
            if decision["decision"] != "include":
                continue
            field, annotation = nodes[identifier], decision["metadata"]["annotation"]
            storage = decision["metadata"]["storage"]
            spelling = storage["type_name"]
            if not re.fullmatch(r"[A-Za-z_]\w*", field["name"], re.ASCII):
                raise PolicyError(
                    "ICG_EMIT_NAME", "field identifier outside the ASCII ABI profile"
                )
            offset, width, shift = int(field["offset_bits"]), 0, 0
            if field["bitfield"]:
                width = int(field["bit_width"])
                shift = 32 - offset % 32 - width
                if (
                    width <= 0
                    or shift < 0
                    or (offset // 32 + 1) * 32 > int(node["size_bits"])
                ):
                    raise PolicyError(
                        "ICG_EMIT_BITFIELD",
                        f"field cannot use the legacy 32-bit storage unit: {name}::{field['name']}",
                    )
                offset = offset // 32 * 4
            else:
                if offset % 8:
                    raise PolicyError(
                        "ICG_EMIT_LAYOUT", "scalar offset is not byte aligned"
                    )
                offset //= 8
                checks.append(
                    f'    static_assert({offset} <= sizeof(::{name}) && sizeof({storage["cpp_type"]}) <= sizeof(::{name}) - {offset}, "ICG field exceeds record storage");\n'
                )
                if decision["metadata"]["access"]["allowed"]:
                    # This is an actual access expression inside the exact
                    # resolved init function. Private fields need its friendship.
                    checks.append(
                        f'    static_assert(offsetof(::{name}, {field["name"]}) == {offset}, "ICG field offset mismatch: {field["name"]}");\n'
                    )
                    checks.append(
                        f'    static_assert(std::is_same<decltype(::{name}::{field["name"]}), {storage["cpp_type"]}>::value, "ICG field type mismatch");\n'
                    )
            structured = storage["trick_type"] == "TRICK_STRUCTURED"
            if structured:
                row = f"attr{symbol}[{len(rows)}]"
                registrations.append(
                    f"    trick_MM->add_attr_info(std::string({row}.type_name), &{row}, __FILE__, __LINE__);\n"
                )
            rows.append(
                attribute(
                    name=field["name"],
                    spelling=spelling,
                    units=annotation["units"],
                    description=annotation["description"],
                    io=annotation["io"],
                    mods=annotation["mods"],
                    kind=storage["trick_type"],
                    size="0"
                    if structured
                    else ("4" if width else f"sizeof({spelling})"),
                    offset=offset,
                    width=width,
                    shift=shift,
                    dimensions=storage["dimensions"],
                )
            )
            units.append(
                f"        map->add_param({literal(decision['metadata']['units_map_key'])}, {literal(annotation['units'])});\n"
            )
        chunks.append(
            'extern "C" {\n'
            + f"ATTRIBUTES attr{symbol}[] = {{\n"
            + ",\n".join(rows + [attribute()])
            + " };\n}\n"
        )
        namespaces = [n for n in contexts(node, nodes) if n["kind"] == "namespace"]
        for namespace in namespaces:
            chunks.append(
                ("inline " if namespace["inline"] else "")
                + f"namespace {namespace['name']} {{\n"
            )
        initialization = ""
        if registrations:
            # Match legacy initialization before recursive MemoryManager lookup.
            initialization = (
                "    static bool initialized = false;\n"
                "    if (initialized) return;\n"
                "    initialized = true;\n" + "".join(registrations)
            )
        chunks.append(
            f"void init_attr{symbol}() {{\n" + "".join(checks) + initialization + "}\n"
        )
        chunks.extend("}\n" for _ in namespaces)
        chunks.append(
            'extern "C" {\n'
            + f"void init_attr{symbol}_c_intf() {{ ::{meta['init_function']}(); }}\n"
            + f"size_t io_src_sizeof_{symbol}() {{ return sizeof(::{name}); }}\n}}\n"
        )
        if units:
            chunks.append(
                "namespace {\n"
                + f"struct UnitsMap{symbol} {{\n    UnitsMap{symbol}() {{\n        auto* map = Trick::UnitsMap::units_map();\n"
                + "".join(units)
                + f"    }}\n}} um{symbol};\n}}\n"
            )
    return "\n".join(chunks)


def write(facts: dict, request: dict, resolved: dict, output: Path) -> bool:
    """Validate/render completely before atomically replacing changed content."""
    content = render(facts, request, resolved).encode("utf-8")
    if output.is_symlink() or output.resolve() in {
        Path(f["path"]["real"]).resolve() for f in facts["files"]
    }:
        raise PolicyError("ICG_EMIT_OUTPUT", "output would replace an input or symlink")
    if output.exists() and output.read_bytes() == content:
        return False
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary = None
    try:
        with tempfile.NamedTemporaryFile(
            dir=output.parent, prefix="." + output.name + ".", delete=False
        ) as stream:
            temporary = Path(stream.name)
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, output)
    finally:
        if temporary is not None:
            temporary.unlink(missing_ok=True)
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("facts", type=Path)
    parser.add_argument("--request", type=Path, required=True)
    parser.add_argument("--resolved", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    try:
        if args.output.resolve() in {
            p.resolve() for p in (args.facts, args.request, args.resolved)
        }:
            raise PolicyError(
                "ICG_EMIT_OUTPUT", "output would overwrite an input document"
            )
        documents = [
            json.loads(p.read_text(encoding="utf-8"))
            for p in (args.facts, args.request, args.resolved)
        ]
        write(*documents, args.output)
    except (ValueError, OSError, policy.ValidationError) as error:
        print(error, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
