# LLVM library selection is separate from the compiler used to build Trick.
if(DEFINED LLVM_DIR AND NOT LLVM_DIR MATCHES "-NOTFOUND$" AND NOT EXISTS "${LLVM_DIR}/LLVMConfig.cmake")
    message(FATAL_ERROR "LLVM_DIR does not contain LLVMConfig.cmake: ${LLVM_DIR}. Select an LLVM development package directory.")
endif()
find_package(LLVM REQUIRED CONFIG)
if(LLVM_PACKAGE_VERSION VERSION_LESS 14)
    message(FATAL_ERROR "Trick ICG requires LLVM >=14; found ${LLVM_PACKAGE_VERSION} at ${LLVM_DIR}.")
endif()
# Distribution and upstream LLVM installs place their config packages side by side.
# Use the selected LLVM's Clang package, never a second PATH search.
file(REAL_PATH "${LLVM_DIR}" llvm_config_dir)
file(REAL_PATH "${llvm_config_dir}/../clang" matching_clang_dir)
if(DEFINED Clang_DIR AND NOT Clang_DIR MATCHES "-NOTFOUND$")
    file(REAL_PATH "${Clang_DIR}" selected_clang_dir)
    if(NOT selected_clang_dir STREQUAL matching_clang_dir)
        message(FATAL_ERROR "LLVM_DIR and Clang_DIR must select sibling config packages from one LLVM installation. LLVM: ${LLVM_DIR}; Clang: ${Clang_DIR}. Select matching packages in a fresh build directory.")
    endif()
endif()
find_package(Clang REQUIRED CONFIG PATHS "${matching_clang_dir}" NO_DEFAULT_PATH)
if(NOT TARGET clangTooling OR NOT TARGET LLVMSupport)
    message(FATAL_ERROR "Selected LLVM/Clang development packages lack clangTooling or LLVMSupport. Install the complete matching development packages.")
endif()
message(STATUS "Trick ICG libraries: LLVM ${LLVM_PACKAGE_VERSION}; LLVM_DIR=${LLVM_DIR}; Clang_DIR=${Clang_DIR}")

find_file(trick_clang_version_header NAMES clang/Basic/Version.inc
    PATHS ${CLANG_INCLUDE_DIRS} ${LLVM_INCLUDE_DIRS} NO_DEFAULT_PATH NO_CACHE)
if(NOT trick_clang_version_header)
    message(FATAL_ERROR "Selected Clang package lacks clang/Basic/Version.inc. Install matching Clang development headers.")
endif()
file(STRINGS "${trick_clang_version_header}" clang_major_line REGEX "^#define CLANG_VERSION_MAJOR [0-9]+$")
string(REGEX REPLACE "^#define CLANG_VERSION_MAJOR ([0-9]+)$" "\\1" clang_major "${clang_major_line}")
string(REGEX MATCH "^[0-9]+" llvm_major "${LLVM_PACKAGE_VERSION}")
if(NOT clang_major STREQUAL llvm_major)
    message(FATAL_ERROR "LLVM/Clang major versions disagree: LLVM ${LLVM_PACKAGE_VERSION}, Clang header ${clang_major} (${trick_clang_version_header}). Select matching development packages.")
endif()
