include_guard(GLOBAL)

set(TRICK_SWIG_MAJOR "4" CACHE STRING "SWIG major (4, or deprecated 3)")
set_property(CACHE TRICK_SWIG_MAJOR PROPERTY STRINGS 4 3)
if(NOT TRICK_SWIG_MAJOR MATCHES "^[34]$")
    message(FATAL_ERROR "TRICK_SWIG_MAJOR must be 3 or 4")
endif()
math(EXPR swig_next_major "${TRICK_SWIG_MAJOR} + 1")
find_package(SWIG ${TRICK_SWIG_MAJOR}.0...<${swig_next_major}.0 QUIET COMPONENTS python)
if(NOT SWIG_FOUND)
    set(swig_help "Install SWIG ${TRICK_SWIG_MAJOR}.x with Python support, or select it with -DSWIG_EXECUTABLE=/path/to/swig and a matching SWIG_DIR.")
    if(TRICK_SWIG_MAJOR STREQUAL "4")
        string(APPEND swig_help " If only SWIG 3 is available, explicitly enable deprecated compatibility with -DTRICK_SWIG_MAJOR=3. SWIG 3 support will be removed in Trick 27.")
    endif()
    message(FATAL_ERROR "Trick requires SWIG ${TRICK_SWIG_MAJOR}.x with Python support. Found version '${SWIG_VERSION}' at '${SWIG_EXECUTABLE}'. ${swig_help}")
endif()
if(SWIG_VERSION VERSION_LESS 4)
    message(WARNING "DEPRECATED: SWIG ${SWIG_VERSION} (${SWIG_EXECUTABLE}) is enabled for compatibility only. Upgrade to SWIG 4 and configure with -DTRICK_SWIG_MAJOR=4. SWIG 3 support will be removed in Trick 27.")
endif()
