# Reviewed output inventory. Transitive dependencies are supplied by ICG depfiles.
set(trick_core_headers
    include/trick/ABM_Integrator.hh
    include/trick/AttributesMap.hh
    include/trick/CheckPointAgent.hh
    include/trick/CheckPointRestart.hh
    include/trick/ClientConnection.hh
    include/trick/Clock.hh
    include/trick/CommandLineArguments.hh
    include/trick/DRAscii.hh
    include/trick/DRBinary.hh
    include/trick/DRHDF5.hh
    include/trick/DataRecordDispatcher.hh
    include/trick/DataRecordGroup.hh
    include/trick/DebugPause.hh
    include/trick/EchoJobs.hh
    include/trick/EnumAttributesMap.hh
    include/trick/Environment.hh
    include/trick/Euler_Cromer_Integrator.hh
    include/trick/Euler_Integrator.hh
    include/trick/Event.hh
    include/trick/EventInstrument.hh
    include/trick/EventManager.hh
    include/trick/EventProcessor.hh
    include/trick/Executive.hh
    include/trick/ExecutiveException.hh
    include/trick/ExternalApplication.hh
    include/trick/Flag.h
    include/trick/FrameDataRecordGroup.hh
    include/trick/FrameLog.hh
    include/trick/GetTimeOfDayClock.hh
    include/trick/IPPython.hh
    include/trick/IPPythonEvent.hh
    include/trick/ITimer.hh
    include/trick/InputProcessor.hh
    include/trick/InstrumentBase.hh
    include/trick/IntegLoopManager.hh
    include/trick/IntegLoopScheduler.hh
    include/trick/IntegLoopSimObject.hh
    include/trick/Integrator.hh
    include/trick/JITEvent.hh
    include/trick/JITInputFile.hh
    include/trick/JSONVariableServer.hh
    include/trick/JSONVariableServerThread.hh
    include/trick/JobData.hh
    include/trick/MM4_Integrator.hh
    include/trick/MSConnect.hh
    include/trick/MSSharedMem.hh
    include/trick/MSSocket.hh
    include/trick/MTV.hh
    include/trick/MalfunctionsTrickView.hh
    include/trick/Master.hh
    include/trick/MemoryManager.hh
    include/trick/MessageCout.hh
    include/trick/MessageCustomFile.hh
    include/trick/MessageCustomManager.hh
    include/trick/MessageFile.hh
    include/trick/MessageHSFile.hh
    include/trick/MessageLCout.hh
    include/trick/MessagePublisher.hh
    include/trick/MessageSubscriber.hh
    include/trick/MessageTCDevice.hh
    include/trick/MessageThreadedCout.hh
    include/trick/MonteCarlo.hh
    include/trick/MonteMonitor.hh
    include/trick/MonteVar.hh
    include/trick/MultiDtIntegLoopScheduler.hh
    include/trick/MultiDtIntegLoopSimObject.hh
    include/trick/MulticastGroup.hh
    include/trick/NL2_Integrator.hh
    include/trick/PlaybackFile.hh
    include/trick/RK2_Integrator.hh
    include/trick/RK4_Integrator.hh
    include/trick/RKF45_Integrator.hh
    include/trick/RKF78_Integrator.hh
    include/trick/RKG4_Integrator.hh
    include/trick/RealtimeSync.hh
    include/trick/RemoteShell.hh
    include/trick/RtiEvent.hh
    include/trick/RtiExec.hh
    include/trick/RtiList.hh
    include/trick/RtiStager.hh
    include/trick/STLInterface.hh
    include/trick/ScheduledJobQueue.hh
    include/trick/Scheduler.hh
    include/trick/Sie.hh
    include/trick/SimControlPanel.hh
    include/trick/SimObject.hh
    include/trick/SimTime.hh
    include/trick/Slave.hh
    include/trick/StripChart.hh
    include/trick/SysThread.hh
    include/trick/SystemInterface.hh
    include/trick/TCPClientListener.hh
    include/trick/TCPConnection.hh
    include/trick/ThreadBase.hh
    include/trick/ThreadTrigger.hh
    include/trick/Threads.hh
    include/trick/Timer.hh
    include/trick/TrickView.hh
    include/trick/UCFn.hh
    include/trick/UDPConnection.hh
    include/trick/UdUnits.hh
    include/trick/Unit.hh
    include/trick/UnitTest.hh
    include/trick/UnitsMap.hh
    include/trick/VariableReference.hh
    include/trick/VariableServer.hh
    include/trick/VariableServerListenThread.hh
    include/trick/VariableServerSession.hh
    include/trick/VariableServerSessionThread.hh
    include/trick/Zeroconf.hh
    include/trick/attributes.h
    include/trick/dllist.h
    include/trick/io_alloc.h
    include/trick/lqueue.h
    include/trick/lstack.h
    include/trick/mc_master.hh
    include/trick/mc_python_code.hh
    include/trick/mc_variable.hh
    include/trick/mc_variable_file.hh
    include/trick/mc_variable_fixed.hh
    include/trick/mc_variable_random.hh
    include/trick/mc_variable_random_bool.hh
    include/trick/mc_variable_random_normal.hh
    include/trick/mc_variable_random_string.hh
    include/trick/mc_variable_random_uniform.hh
    include/trick/mc_variable_semi_fixed.hh
    include/trick/message_type.h
    include/trick/mm_error.h
    include/trick/ms_sim_mode.h
    include/trick/parameter_types.h
    include/trick/rand_generator.h
    include/trick/reference.h
    include/trick/reference_frame.h
    include/trick/regula_falsi.h
    include/trick/sim_mode.h
    include/trick/tc.h
    include/trick/time_offset.h
    include/trick/trick_error_hndlr.h
    include/trick/tsm.h
    include/trick/units_conv.h
    include/trick/value.h
    include/trick/var.h
    include/trick/variable_server_message_types.h
    include/trick/variable_server_sync_types.h
    include/trick/wave_form.h
)
if(TRICK_USE_ER7_UTILS)
    list(APPEND trick_core_headers
        trick_source/er7_utils/integration/abm4/include/abm4_first_order_ode_integrator.hh
        trick_source/er7_utils/integration/abm4/include/abm4_integrator_constructor.hh
        trick_source/er7_utils/integration/abm4/include/abm4_second_order_ode_integrator.hh
        trick_source/er7_utils/integration/beeman/include/beeman_integrator_constructor.hh
        trick_source/er7_utils/integration/beeman/include/beeman_second_order_ode_integrator.hh
        trick_source/er7_utils/integration/core/include/base_integration_group.hh
        trick_source/er7_utils/integration/core/include/bogus_integration_controls.hh
        trick_source/er7_utils/integration/core/include/first_order_ode_integrator.hh
        trick_source/er7_utils/integration/core/include/generalized_position_derivative.hh
        trick_source/er7_utils/integration/core/include/integrable_object.hh
        trick_source/er7_utils/integration/core/include/integration_controls.hh
        trick_source/er7_utils/integration/core/include/integration_messages.hh
        trick_source/er7_utils/integration/core/include/integration_technique.hh
        trick_source/er7_utils/integration/core/include/integrator_constructor.hh
        trick_source/er7_utils/integration/core/include/integrator_constructor_factory.hh
        trick_source/er7_utils/integration/core/include/integrator_interface.hh
        trick_source/er7_utils/integration/core/include/integrator_result.hh
        trick_source/er7_utils/integration/core/include/integrator_result_merger.hh
        trick_source/er7_utils/integration/core/include/integrator_result_merger_container.hh
        trick_source/er7_utils/integration/core/include/left_quaternion_functions.hh
        trick_source/er7_utils/integration/core/include/priming_first_order_ode_integrator.hh
        trick_source/er7_utils/integration/core/include/priming_integration_controls.hh
        trick_source/er7_utils/integration/core/include/priming_integrator_constructor.hh
        trick_source/er7_utils/integration/core/include/priming_second_order_ode_integrator.hh
        trick_source/er7_utils/integration/core/include/second_order_ode_integrator.hh
        trick_source/er7_utils/integration/core/include/single_cycle_integration_controls.hh
        trick_source/er7_utils/integration/core/include/standard_integration_controls.hh
        trick_source/er7_utils/integration/core/include/state_integrator.hh
        trick_source/er7_utils/integration/core/include/time_interface.hh
        trick_source/er7_utils/integration/euler/include/euler_first_order_ode_integrator.hh
        trick_source/er7_utils/integration/euler/include/euler_integrator_constructor.hh
        trick_source/er7_utils/integration/euler/include/euler_second_order_ode_integrator.hh
        trick_source/er7_utils/integration/mm4/include/mm4_integrator_constructor.hh
        trick_source/er7_utils/integration/mm4/include/mm4_second_order_ode_integrator.hh
        trick_source/er7_utils/integration/nl2/include/nl2_integrator_constructor.hh
        trick_source/er7_utils/integration/nl2/include/nl2_second_order_ode_integrator.hh
        trick_source/er7_utils/integration/position_verlet/include/position_verlet_integrator_constructor.hh
        trick_source/er7_utils/integration/position_verlet/include/position_verlet_second_order_ode_integrator.hh
        trick_source/er7_utils/integration/rk2_heun/include/rk2_heun_first_order_ode_integrator.hh
        trick_source/er7_utils/integration/rk2_heun/include/rk2_heun_integrator_constructor.hh
        trick_source/er7_utils/integration/rk2_heun/include/rk2_heun_second_order_ode_integrator.hh
        trick_source/er7_utils/integration/rk2_midpoint/include/rk2_midpoint_first_order_ode_integrator.hh
        trick_source/er7_utils/integration/rk2_midpoint/include/rk2_midpoint_integrator_constructor.hh
        trick_source/er7_utils/integration/rk2_midpoint/include/rk2_midpoint_second_order_ode_integrator.hh
        trick_source/er7_utils/integration/rk4/include/rk4_first_order_ode_integrator.hh
        trick_source/er7_utils/integration/rk4/include/rk4_integrator_constructor.hh
        trick_source/er7_utils/integration/rk4/include/rk4_second_order_ode_integrator.hh
        trick_source/er7_utils/integration/rk4/include/rk4_second_order_ode_integrator_base.hh
        trick_source/er7_utils/integration/rkf45/include/rkf45_first_order_ode_integrator.hh
        trick_source/er7_utils/integration/rkf45/include/rkf45_integrator_constructor.hh
        trick_source/er7_utils/integration/rkf45/include/rkf45_second_order_ode_integrator.hh
        trick_source/er7_utils/integration/rkf78/include/rkf78_first_order_ode_integrator.hh
        trick_source/er7_utils/integration/rkf78/include/rkf78_integrator_constructor.hh
        trick_source/er7_utils/integration/rkf78/include/rkf78_second_order_ode_integrator.hh
        trick_source/er7_utils/integration/rkg4/include/rkg4_first_order_ode_integrator.hh
        trick_source/er7_utils/integration/rkg4/include/rkg4_integrator_constructor.hh
        trick_source/er7_utils/integration/rkg4/include/rkg4_second_order_ode_integrator.hh
        trick_source/er7_utils/integration/symplectic_euler/include/symplectic_euler_integrator_constructor.hh
        trick_source/er7_utils/integration/symplectic_euler/include/symplectic_euler_second_order_ode_integrator.hh
        trick_source/er7_utils/integration/velocity_verlet/include/velocity_verlet_integrator_constructor.hh
        trick_source/er7_utils/integration/velocity_verlet/include/velocity_verlet_second_order_ode_integrator.hh
        trick_source/er7_utils/interface/include/deletable.hh
        trick_source/er7_utils/math/include/n_choose_m.hh
        trick_source/er7_utils/math/include/ratio128.hh
        trick_source/er7_utils/math/include/uint128.hh
        trick_source/er7_utils/trick/integration/include/trick_first_order_ode_integrator.hh
        trick_source/er7_utils/trick/integration/include/trick_integrator.hh
        trick_source/er7_utils/trick/integration/include/trick_second_order_ode_integrator.hh
    )
endif()
