include_guard(GLOBAL)

# Preflight selections, not promises that later runtime/ICG targets exist yet.
set(TRICK_DEPENDENCY_PROFILE "UTILITIES" CACHE STRING "Dependency preflight: UTILITIES, RUNTIME, ICG, ALL")
set_property(CACHE TRICK_DEPENDENCY_PROFILE PROPERTY STRINGS UTILITIES RUNTIME ICG ALL)
if(NOT TRICK_DEPENDENCY_PROFILE MATCHES "^(UTILITIES|RUNTIME|ICG|ALL)$")
    message(FATAL_ERROR "Invalid TRICK_DEPENDENCY_PROFILE='${TRICK_DEPENDENCY_PROFILE}'; choose UTILITIES, RUNTIME, ICG or ALL.")
endif()

if((NOT TRICK_DEPENDENCY_PROFILE STREQUAL "UTILITIES" OR TRICK_BUILD_ICG OR TRICK_BUILD_MEMORY_MANAGER) AND CMAKE_CROSSCOMPILING)
    message(FATAL_ERROR "Dependency preflight currently requires a native build. Host/target separation for cross builds is introduced in E3.")
endif()

if(TRICK_DEPENDENCY_PROFILE MATCHES "^(RUNTIME|ALL)$")
    include("${CMAKE_CURRENT_LIST_DIR}/TrickRuntimeDependencies.cmake")
endif()
if(TRICK_DEPENDENCY_PROFILE MATCHES "^(ICG|ALL)$" OR TRICK_BUILD_ICG)
    include("${CMAKE_CURRENT_LIST_DIR}/TrickLLVM.cmake")
endif()

if((TRICK_BUILD_ICG OR TRICK_BUILD_MEMORY_MANAGER) AND NOT TARGET UDUNITS2::UDUNITS2)
    list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/modules")
    find_package(UDUNITS2 REQUIRED)
endif()


if(TRICK_BUILD_MEMORY_MANAGER)
    find_package(BISON REQUIRED)
    find_package(FLEX REQUIRED)
    find_package(Threads REQUIRED)
endif()

if(TRICK_BUILD_PYTHON)
    if(DEFINED TRICK_PYTHON_MAJOR AND NOT TRICK_PYTHON_MAJOR STREQUAL "3")
        message(FATAL_ERROR "The native Python runtime supports Python 3. Python 2 remains on the legacy build route during transition.")
    endif()
    if(NOT TARGET Trick::Python)
        include("${CMAKE_CURRENT_LIST_DIR}/TrickPython.cmake")
    endif()
    find_package(SWIG 3.0 REQUIRED COMPONENTS python)
endif()

# Plain-text report avoids serializing arbitrary paths into executable CMake code.
set(report "Trick dependency preflight: ${TRICK_DEPENDENCY_PROFILE}\nCMake: ${CMAKE_VERSION}\nSystem: ${CMAKE_SYSTEM_NAME} ${CMAKE_SYSTEM_VERSION} ${CMAKE_SYSTEM_PROCESSOR}\nGenerator: ${CMAKE_GENERATOR}\nC: ${CMAKE_C_COMPILER} (${CMAKE_C_COMPILER_ID} ${CMAKE_C_COMPILER_VERSION})\nCXX: ${CMAKE_CXX_COMPILER} (${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION})\n")
string(APPEND report "ICG: ${TRICK_BUILD_ICG}\nMemory manager: ${TRICK_BUILD_MEMORY_MANAGER}\nIntegrators: ${TRICK_BUILD_INTEGRATORS} (ER7 ${TRICK_USE_ER7_UTILS})\nCore metadata: ${TRICK_BUILD_CORE_METADATA}\nCore runtime: ${TRICK_BUILD_CORE}\nPython input: ${TRICK_BUILD_PYTHON}\n")
set(report_variables)
if(TRICK_BUILD_MEMORY_MANAGER)
    list(APPEND report_variables BISON_EXECUTABLE BISON_VERSION FLEX_EXECUTABLE FLEX_VERSION)
endif()
if(TRICK_BUILD_PYTHON)
    list(APPEND report_variables SWIG_EXECUTABLE SWIG_VERSION Python3_EXECUTABLE Python3_VERSION Python3_INCLUDE_DIRS Python3_LIBRARIES)
endif()
if(TRICK_DEPENDENCY_PROFILE MATCHES "^(RUNTIME|ALL)$")
    list(APPEND report_variables BISON_EXECUTABLE BISON_VERSION FLEX_EXECUTABLE FLEX_VERSION SWIG_EXECUTABLE SWIG_VERSION PERL_EXECUTABLE PERL_VERSION_STRING TRICK_PYTHON_MAJOR
        ${python_package}_EXECUTABLE ${python_package}_VERSION ${python_package}_INCLUDE_DIRS ${python_package}_LIBRARIES UDUNITS2_INCLUDE_DIR UDUNITS2_LIBRARY)
endif()
if(TRICK_DEPENDENCY_PROFILE MATCHES "^(ICG|ALL)$" OR TRICK_BUILD_ICG)
    list(APPEND report_variables LLVM_DIR LLVM_PACKAGE_VERSION Clang_DIR)
endif()
if(TRICK_BUILD_ICG)
    list(APPEND report_variables UDUNITS2_INCLUDE_DIR UDUNITS2_LIBRARY)
endif()
list(REMOVE_DUPLICATES report_variables)
foreach(variable IN LISTS report_variables)
    if(DEFINED ${variable})
        string(APPEND report "${variable}: ${${variable}}\n")
    endif()
endforeach()
file(WRITE "${PROJECT_BINARY_DIR}/TrickDependencies.txt" "${report}")
message(STATUS "Trick dependency profile: ${TRICK_DEPENDENCY_PROFILE}; details: ${PROJECT_BINARY_DIR}/TrickDependencies.txt")
